#!/bin/bash
REMOTENAME=$1
LOCALNAME=$2
CLIP=$3

    
outfile=${LOCALNAME}_${CLIP}
if [ -e ${outfile}.avi ]; then
  echo ${outfile}.avi already exists. Skipping
else
  infile1=rtsp://rmv8.bbc.net.uk/comedy/${REMOTENAME}/bb/${CLIP}_16x9_bb.rm
  infile2=rtsp://rmv8.bbc.net.uk/comedy/${REMOTENAME}/bb/${REMOTENAME}_${CLIP}_16x9_bb.rm
  infile3=rtsp://rmgeo.bbc.net.uk/bbcthree/${REMOTENAME}/bb/${REMOTENAME}_s0${j}_ep0${i}_16x9_bb.rm
  for infile in ${infile1} ${infile2} ${infile3}; do
    if [ -e ${outfile}.avi ]; then
      echo Â${outfile}.avi already exists. Skipping
    else
      if [ -e ${outfile}.rm ]; then
        echo ${outfile}.rm already exists. Skipping download.
      else
        mplayer -prefer-ipv4 -noframedrop -dumpfile ${outfile}.rm -dumpstream ${infile}
      fi
      mencoder ${outfile}.rm -ovc lavc -oac pcm -o ${outfile}.avi
      if [ -e ${outfile}.avi ]; then
        rm ${outfile}.rm
      fi
    fi
  done
fi
