#!/usr/bin/env ruby
require 'rake'
require 'spec/rake/spectask'
require 'spec/rake/verify_rcov'

desc "Run all tests with RCov"
Spec::Rake::SpecTask.new('rcov') do |t|
  t.spec_files    = FileList['spec/**/*.rb']
  t.rcov          =true
  t.rcov_opts     =['--exclude', 'spec,test']
  t.spec_opts     = ["--format", "html:doc/output/rspec_report.html", "--diff"]
  t.fail_on_error = false

end
RCov::VerifyTask.new(:verify_rcov => :spec) do |t|
  t.threshold  = 100.0 # Make sure you have rcov 0.7 or higher!
  t.index_html = 'doc/output/coverage/index.html'
end

